### PR TITLE
[4.x] build: bump node-sass from 4.13.0 to 6.0.1

### PR DESCRIPTION
**Pull request by pure-js**
It's necessary for the latest Node.js LTS build (16.13.0) support.
In other case `yarn install` command will crash

### CODE REVIEW

**Comment by justin808** [comment]
@pure-js why not just upgrade?

**Comment by justin808** [comment]
@guillaumebriday What is the policy on making updates to old branches? I think if the fix can be done by one's config, that's good enough, such as this one, using resolutions.

@pure-js You can use https://classic.yarnpkg.com/lang/en/docs/selective-version-resolutions/ to set the version for node-sass for your project.

@guillaumebriday reopen if you see fit.

**Comment by ghiculescu** [comment]
I think this is a bigger issue since https://devcenter.heroku.com/changelog-items/2306

**Comment by justin808** [comment]
> Applications using the heroku/ruby buildpack that do not have a version of Node installed by another buildpack (such as the heroku/nodejs buildpack) will now receive:

Thus, you **should** use the heroku/nodejs buildpack.

**Pull request closed without merging**
