### PR TITLE
Fix image_pack_tag with srcset does not compute relative path correctly

### LINKED ISSUE #2539: image_pack_tag with srcset does not compute relative path correctly
Example:

```ruby
image_pack_tag('mypicture.png', srcset: { 'mypicture-2x.png' => '2x' })
```

Actual:

```html
<img src="/media/images/mypicture-7cca48e6cae66ec07b8ee0db62bbef6.png" srcset= "/images/mypicture-2x.png 2x">
```

Expected:

```html
<img src="/media/images/mypicture-7cca48e6cae66ec07b8ee0db62bbef6.png" srcset= "/media/images/mypicture-2x-9bcc3bef4c080665d829f495fabc8647.png 2x">
```

### PR DESCRIPTION
**Pull request by deepj**
Closes #2539

### CODE REVIEW

**Comment by gauravtiwari** [comment]
Could you please get the tests passing? Thanks

**Comment by deepj** [comment]
@gauravtiwari that's rubocop, not the tests themselves

**Comment by gauravtiwari** [comment]
Oh yes, can you please make rubocop happy and I will merge once CI passes.

**Comment by deepj** [comment]
@gauravtiwari fixed and passed

**Comment by gauravtiwari** [comment]
thank you!

**Pull request merged**
