### PR TITLE
Minify production builds with uglifyjs

### PR DESCRIPTION
**Pull request by schpet**
for smaller production builds and to support tree shaking (#36)

### CODE REVIEW

**Comment by guilleiguaran** [comment]
wait, one second...

The files were being compressed already before of merging this?

**Comment by schpet** [comment]
@guilleiguaran i don't think the files were being compressed by default for some reason. you either have to run webpack with `-p` or`--optimize-minimize` flag, or set this up in the webpack.config. i can try and confirm this behavior with a demo if that would be helpful to you.

**Comment by schpet** [comment]
#132 has  this same change, and also gzipping which makes sense

**Comment by guilleiguaran** [comment]
yup, I didn't noticed #132 before, now it needs to be rebased before of merge, will try to do it now

**Pull request merged**
