### PR TITLE
Added info about necessity of commenting uglifier

### PR DESCRIPTION
**Pull request by timonbandit**
Hey @gauravtiwari 
PR relating to #1061

### CODE REVIEW

**Comment by guilleiguaran** [comment]
I think this should be mentioned in the [troubleshooting docs](https://github.com/rails/webpacker/blob/master/docs/troubleshooting.md) and that this is a problem only when you want to share files between Sprockets and Webpacker so it isn't always the case.

**Comment by timonbandit** [comment]
@guilleiguaran Thank you.
You're right, i will make the new one commit

**Comment by timonbandit** [comment]
@guilleiguaran - updated!

**Comment by gauravtiwari** [comment]
@timonbandit Pushed a small update. Does that look alright to you?

**Comment by timonbandit** [comment]
@gauravtiwari Yes. looks good! ;)

**Comment by gauravtiwari** [comment]
great, thanks 🍰

**Pull request merged**
