### PR TITLE
Use APP_PATH when searching for webpack bin

### PR DESCRIPTION
**Pull request by garbles**

### CODE REVIEW

**Comment by Nitrino** [comment]
`node_modules` installed in the vendor directory. 
It should look like this:
`WEBPACK_BIN = "#{VENDOR_PATH}/node_modules/webpack/bin/webpack.js"`
or in this case, quite right:
`WEBPACK_BIN    = "./node_modules/webpack/bin/webpack.js"`

**Comment by guilleiguaran** [comment]
@Nitrino is right, `node_modules` is not in `APP_PATH` in Rails 5.1 apps

**Comment by garbles** [comment]
Ah yup. `bin/yarn` did not exist in the project. Thanks!

**Comment by Nitrino** [comment]
@garbles see this PR about yarn binstub #9

**Pull request closed without merging**
