### PR TITLE
Use config digests path within rake

### PR DESCRIPTION
**Pull request by merqlove**
Subj

### CODE REVIEW

**Comment by merqlove** [comment]
Looks like default value is needed for `:digests_path`

**Comment by dhh** [comment]
One is provided in https://github.com/rails/webpacker/blob/f4cc31d445e54300d48e381b0381d87d31204588/lib/webpacker/railtie.rb#L15, but not initialized as such. So yeah, need to initialize that before using it here.

**Comment by merqlove** [comment]
Ok, also i think fix up chunk names fetcher. 
In the case when we do production build with SourceMaps (i.e. for Rollbar, ...), here is `Array` per pack:
`["chunk name.js", "chunk_name.js.map"]`, instead of `"chunk name.js"`. 
I have this fix local already.

**Comment by merqlove** [comment]
I have pushed few optimizations, maybe best to have it as single PR?

https://github.com/merqlove/webpacker/tree/develop

Features:
- Shared options per webpack config.
- Defaults for `:digests_path`.
- `:packs_dist_path`: Destination folder, useful way to extract production builds and/or change location of dev build.
- Fixed per chunk `array` problem, when we building SourceMaps in prod.

Cleanup

**Comment by merqlove** [comment]
Link to compare: https://github.com/rails/webpacker/compare/master...merqlove:develop?expand=1

**Comment by merqlove** [comment]
So, seems that https://github.com/rails/webpacker/pull/67 is better. I will close current for now,

**Pull request closed without merging**
