### PR TITLE
Rename environment loaders to environment rules

### LINKED ISSUE #2257: Rename `environment.loaders` to `environment.rules`
I was unable to find an existing issue regarding this, but if there is one, my apologies.

Why is the set of Webpack rules referred to as `loaders`? Since rules _include_ loaders, it generates a lot of confusion. It would probably also make sense to change some of the internal api as well (e.g. rename `getLoaderList` to `getRuleList`, etc.)

### PR DESCRIPTION
**Pull request by HarrisonB**
Closes #2257.

I don't have a CHANGELOG entry--is something I would do in this pull request?

### CODE REVIEW

**Comment by jakeNiemiec** [comment]
Thank you for going to all that trouble! 

> I don't have a CHANGELOG entry--is something I would do in this pull request?

Yes, but this would be a breaking change since users will need to manually update their `environment.js` file. I would put instructions for these required changes under a 4.1 header.

**Comment by HarrisonB** [comment]
> I would put instructions for these required changes under a 4.1 header.

Done in https://github.com/rails/webpacker/pull/2271/commits/2ea2ce8d926c2ee82af68f0b32c8179817872629. Wasn't sure what to put for dates so I left a `?`...

**Comment by jakeNiemiec** [comment]
I talked to Gaurav, this will need to be for webpacker 5.x

**Comment by HarrisonB** [comment]
So I suppose this will need to target 6.0.0 now?

**Comment by gauravtiwari** [comment]
@HarrisonB Thanks for working on this. If you could please update, I can review and merge.

**Comment by gauravtiwari** [comment]
@HarrisonB Hey, will you have sometime to look into this? Happy for it to go in 6.0

**Comment by HarrisonB** [comment]
Have next week off as a matter of fact! Will get it ready very soon.
Raymond Berger <notifications@github.com> wrote:
“@HarrisonB Hey, will you have sometime to look into this? Happy for it to go in 6.0”

**Comment by gauravtiwari** [comment]
No worries, thank you.

**Comment by HarrisonB** [comment]
Ready for another look

**Comment by HarrisonB** [comment]
Can I ask why this was closed?

**Comment by jakeNiemiec** [comment]
I think this is covered by https://github.com/rails/webpacker/pull/2826

**Pull request closed without merging**
