### PR TITLE
Set the value of NODE_ENV for compilation from RAILS_ENV. 

### PR DESCRIPTION
**Pull request by lilfaf**
Supports custom rails environments (ex. staging). Much appreciated during
Capistrano deployments.

### CODE REVIEW

**Comment by dleavitt** [comment]
`NODE_ENV` has special meaning to React, Vue and other frontend frameworks, where setting it to `production` disables dev mode.

So more often than not `NODE_ENV` should be `production` even in environments where `RAILS_ENV` is set to something else (like `staging`.)

**Comment by ytbryan** [comment]
@dleavitt actually some tools like vue-devtools are disabled in production mode and only works in dev mode. Is there example of those "special meaning"? 


I am not sure if it is best to set `NODE_ENV` to `ENV['RAILS_ENV']` or product by default.
Maybe there should be a `ENV['NODE_ENV']`?

**Comment by gauravtiwari** [comment]
@dleavitt Agree.  @ytbryan with special meaning he means - 

1. https://facebook.github.io/react/docs/optimizing-performance.html#use-the-production-build
2. https://vuejs.org/v2/guide/deployment.html#With-Build-Tools

The compile task is made for deployments (production or staging), much like `assets:precompile` task and regardless of env it should always be production because both staging and production are expected same in behaviour. As for development, the setup is different - we got watcher and dev-server and they will build assets for us when run.

**Comment by gauravtiwari** [comment]
@lilfaf Is this still a issue for you? You could always set the `NODE_ENV=production` unless in development. The compile task will set this anyway.

**Comment by gauravtiwari** [comment]
Feel free to close if this no longer is a problem 👍

**Comment by gauravtiwari** [comment]
This can be closed as per #197

**Comment by lilfaf** [comment]
@gauravtiwari oh sorry I missed your comment. Indeed this issue could be closed as its not a problem anymore. 👍

**Pull request closed without merging**
