### PR TITLE
bump compression-webpack-plugin to ^4.0.0

### PR DESCRIPTION
**Pull request by akoskm**
https://github.com/rails/webpacker/issues/2693

### CODE REVIEW

**Comment by akoskm** [comment]
@gauravtiwari I made this PR on top of https://github.com/rails/webpacker/tree/4-x-stable as you suggested. The build failures are the same for each job https://travis-ci.org/github/rails/webpacker/jobs/717516894 did I mess up something?

**Comment by DeeDeeG** [comment]
The build failure also happens on the stable branch this PR is made against.

https://travis-ci.org/github/rails/webpacker/builds/665541517

I'm confused what happens to cause this. CI updates bundler to latest (v2) and rubygems to latest, then uses that to install a copy of bundler v1.17.3, but Bundler 2 can't find bundler v1.3.0+?

https://travis-ci.org/github/rails/webpacker/jobs/665541518#L1044-L1055

Maybe trying to install Rails ~4.2.0 with bundlr v2 will always fail? In which case I suppose CI should ensure it does not install Bundler v2 on this branch. Not 100% sure, but maybe that's it.

**Comment by DeeDeeG** [comment]
CI configs have a comment that is referring to this problem and explaining how it attempts to fix it.

https://github.com/rails/webpacker/blob/8db818bb214497a54791b9ebd2e604594ee0eca9/.travis.yml#L3-L9

The problem is, bundler v2 is used anyhow.

Thinking out loud:

I think `gem install rubygems-update && update_rubygems` is installing bundler v2. We don't want that, apparently.

According to [this StackOverflow answer](https://stackoverflow.com/a/37149817), it's probably better to do `gem update --system` if we need updated rubygems, then install bundler v1.17.3.

**_NOT_** `gem install rubygems-update && update_rubygems`.

(We may be able to skip updating Rubygems alotgether, but I'm not sure unless somebody tries it and it works).

**Comment by DeeDeeG** [comment]
I have a fix that appears to be working.

commit: https://github.com/DeeDeeG/webpacker/commit/b21cb2536fe1f22a96d6ceb12d7c3b4be1232267

CI: https://travis-ci.com/github/DeeDeeG/webpacker/builds/179666602

**Comment by DeeDeeG** [comment]
Unrelated to this PR (`compression-webpack-plugin` bump), there is a genuine install failure for the combination of Rails 5.1.x and Ruby 4.2.

There is an unconstrained `sprockets` dependency, which resolves to the latest `sprockets` (`sprockets` 4), which does require Ruby 2.5 or newer.

https://rubygems.org/gems/sprockets/versions/4.0.0

I'm suprised bundler isn't clever enough to just use an older `sprockets`? These are unsupported older versions of Rails _and_ Ruby, so I'm not sure being able to install Rails 5.1 under Ruby 4.2 is this repo's responsibility.

Still, I wonder if this would be fixed with latest `rubygems`. I might see if I can get that last failure to go away, but it's not related to this PR, or even this repo, not really.

**Comment by akoskm** [comment]
@DeeDeeG thanks, it looks like a flake to me. There is a timeout error in the log:
```
Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::UnknownHostError timed out (https://rubygems.org/gems/unicode-display_width-1.5.0.gem)
```
probably Travis couldn't fetch a package during the build. Unfortunately, I cannot rerun the build.

**Comment by gauravtiwari** [comment]
released: 4.3.0

**Comment by ansonhoyt** [comment]
Why would this go into `4-x-stable` when it isn't until 5.0.0 that webpacker drops Node 8 support? This is a breaking change (though I admit Node 8 is now EOL). See [compression-webpack-plugin 4.0.0 changelog](https://github.com/webpack-contrib/compression-webpack-plugin/blob/master/CHANGELOG.md).

We have a few things running on older servers, so this change means we'll need to pin webpacker to `~4.2.0` (or mess with "resolutions" in package.json) until we get around to updating them.

**Pull request merged**
