### PR TITLE
Add cssnext and remove PreCSS

### PR DESCRIPTION
**Pull request by djforth**
As mentioned in #315.

I've added postcss-cssnext and remove PreCSS.  I also removed autoprefixer as it included in cssnext and will cause issues if loaded twice

### CODE REVIEW

**Comment by guilleiguaran** [comment]
Can you remove the changes in Gemfile.lock and test/test_app/log/development.log from this commit?

**Comment by djforth** [comment]
Looks like the log wasn't in the previous commits so have just removed it.  and reset the gemfile.lock back.

**Comment by gauravtiwari** [comment]
I think we also need to update css next section in README - https://github.com/rails/webpacker#css-next

**Comment by renchap** [comment]
I am not sure why I am getting this error, but after updating to the latest `master` I got a PostCSS error saying that the `cssnext` module was not found.

I tried using `postcss-cssnext` (and not `cssnext`) in my `.postcssrc.yml` config file and it works fine. Not sure why it worked for you and not for me.

**Pull request merged**
