### PR TITLE
Use ruby/setup-ruby@v1 for Github Actions

### PR DESCRIPTION
**Pull request by pustovalov**
https://github.com/ruby/setup-ruby - supports `ruby-head`

Example:
https://github.com/pustovalov/webpacker/actions/runs/124153726

### CODE REVIEW

**Comment by gauravtiwari** [comment]
Can we get the failing test passing or is that intended?

**Comment by pustovalov** [comment]
I'll see what can be done, but this problem was before

**Comment by pustovalov** [comment]
My guess is that something is wrong with `test_app` config

If remove:
```
Rails.application.initialize!
```
in `test/test_app/config/environment.rb`

this error is gone

https://github.com/pustovalov/webpacker/runs/788584397?check_suite_focus=true

but what is wrong is not yet clear

error:
```
/home/runner/bundle/ruby/2.8.0/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/static.rb:111:in `initialize': wrong number of arguments (given 3, expected 2) (ArgumentError)
```

https://github.com/rails/rails/blob/5-2-stable/actionpack/lib/action_dispatch/middleware/static.rb#L111

any suggestion? (the difficulties are added by the fact that I can’t install `nokogiri` gem with `ruby-head` on local mac)

**Comment by justin808** [comment]
@gauravtiwari @pustovalov is ruby-head is not supported by Rails? I don't see why we should bother with ruby-head given the nature and purpose of this gem.

**Comment by pustovalov** [comment]
@justin808 

Rails runs its tests for ruby-head

https://buildkite.com/rails/rails/builds/70815
https://buildkite.com/rails/rails/builds/70815#b9aaad41-7a14-4a36-b9d1-0be471da1cd1

**Pull request merged**
