### PR TITLE
fixing typo

### PR DESCRIPTION
**Pull request by VRRmax**
comments in .erb is with <%# ... %>

### CODE REVIEW

**Comment by jakeNiemiec** [comment]
See: https://github.com/rails/webpacker/pull/2263

**Comment by VRRmax** [comment]
I don't understand why you use **<%%=** instead of **<%#=** which is the standard way for ERB commenting. That's the point of my PR, which is different than the one you pointed to me.
**<%%=** looks like a typo, and you will have PR again and again, people thinking you meant '<%=' by '<%%='.

Please tell me if I have a misconception somewhere.

**Comment by VRRmax** [comment]
https://github.com/rails/webpacker/issues/1382#issuecomment-604475039

**Comment by olleolleolle** [comment]
The `%%` is meant to be there, so that the output can be visible to the user reading it as `%`.

The output text is a JS comment to be read by the developer learning from the example.

Hope this helps explain why the `%%` is not a typo.

**Pull request closed without merging**
