### PR TITLE
Fix Vue example import path

### PR DESCRIPTION
**Pull request by hzchirs**
Fix example relative path of app.vue

### CODE REVIEW

**Comment by ytbryan** [comment]
The relative path is correct in the latest hello_vue.js 

https://github.com/rails/webpacker/blob/master/lib/install/examples/vue/hello_vue.js
 
cc @gauravtiwari

**Comment by nholden** [comment]
I needed to make this change in my project to get started. The PR looks good to me!

> The relative path is correct in the latest hello_vue.js

The relative path is correct in [the first example](https://github.com/rails/webpacker/blob/master/lib/install/examples/vue/hello_vue.js#L9) but not in [the second example](https://github.com/rails/webpacker/blob/master/lib/install/examples/vue/hello_vue.js#L36).

**Comment by ytbryan** [comment]
oops, misread..  this should be merged cc @gauravtiwari when you have time.

**Comment by gauravtiwari** [comment]
Apologies, I was away. Merged 🎉

**Pull request merged**
