### PR TITLE
Update README.md to add more TypeScript integration information

### PR DESCRIPTION
**Pull request by noelrappin**
I think you also need to change the preset to use TypeScript -- at least I needed to do this to get my TypeScript files to compile correctly.

### CODE REVIEW

**Comment by gauravtiwari** [comment]
Hi, @noelrappin Is this for webpacker 6.0? We already include this preset automatically if installed (https://github.com/rails/webpacker/blob/master/package/babel/preset.js#L32)

**Comment by noelrappin** [comment]
It is for 6.0, I'll check again, but I definitely had to add it manually to get mine to work.

**Comment by scottrobertson** [comment]
@noelrappin make sure it's not in your `devDependencies`. Needs to be in `dependencies` for Heroku to work for example.

**Comment by noelrappin** [comment]
It is definitely in my `dependencies`. Is it possible it was interacting badly because I had changed the `presets` in my `package.json`?

**Comment by noelrappin** [comment]
My mistake here was specifying the version as `^6.0.0-beta.2`, which gave me `6.0.0-pre1` rather than `6.0.0-beta.2`, specifying it exactly solved the problem.

**Comment by noelrappin** [comment]
Actually I'm going to add one more thing:

My code

**Comment by scottrobertson** [comment]
@noelrappin i think you have 1 too many arrays inside there. For example, mine is:

```
  "babel": {
    "presets": [
      "./node_modules/@rails/webpacker/package/babel/preset.js"
    ]
  },
  ```

**Comment by pedrofurtado** [comment]
Hey, @noelrappin and @scottrobertson  ! 👋 

Considering the latest 6.x version (at this moment is 6.0.0-beta.5), did you have to change some additional configuration to integrate with typescript? 

If so, could you please rebase/sync PR to provide this additional configuration? Depending of changes, we can split some of them to README.md (for fresh installation) and in 6_0_upgrade.md (for upgrading process to 6.x) 🤝 

Anyway, the gem already includes some presets and so on, if the package is installed in node_modules folder, just like mentioned by @gauravtiwari 👍

**Comment by guillaumebriday** [comment]
Hey @noelrappin,

I'm closing the PR for now because it seems already available in Webpacker 6.x. Feel free to fix conflicts and reopen if needed 🙏

**Pull request closed without merging**
