### PR TITLE
CSP warning for Rails 5.2

### PR DESCRIPTION
**Pull request by savroff**
https://github.com/rails/webpacker/issues/1200

screenshot 2018-01-23 11 17 56

### CODE REVIEW

**Comment by guilleiguaran** [comment]
For Angular and Vue we can mention to `p.script_src` also

**Comment by gauravtiwari** [comment]
Thanks @savroff I guess we can keep it simple and remove `-----` around code - an extra lb would do just fine. What do you think?

**Comment by savroff** [comment]
@guilleiguaran I thought about this too :) nice

@gauravtiwari  sure! Just did it to have more readable code example

**Comment by gauravtiwari** [comment]
Also, don't think we need to add same message in all installers unless it's specific to that installer (vue and angular). Since base installers runs first it's fine to just add `connect_src` block there.

**Comment by savroff** [comment]
Seems like everything should be ok now

**Comment by savroff** [comment]
@gauravtiwari thank you! 🎉

**Comment by guilleiguaran** [comment]
Thanks for working on this!!!

**Pull request merged**
