### PR TITLE
Fix a typo in docs/v4-upgrade.md

### PR DESCRIPTION
**Pull request by TomasBarry**

### CODE REVIEW

**Comment by TomasBarry** [comment]
@gauravtiwari should the line then read `Browser support definitions have been moved to [`.browserslistrc`](../lib/install/config/.browserslistrc) from `/`.`?

**Comment by gauravtiwari** [comment]
At the moment it reads, 

> "Browser support definitions have been moved to .browserslistrc."

which I guess is fine?

**Comment by TomasBarry** [comment]
It currently reads
```text
Browser support definitions have been moved to .browserslistrc to /.
```

The end (`to /`) is the problem?

**Comment by gauravtiwari** [comment]
thanks :)

**Pull request merged**
