### PR TITLE
Update webpack-dev-server

### PR DESCRIPTION
**Pull request by makerus**
Add hack for work on Windows

### CODE REVIEW

**Comment by gauravtiwari** [comment]
@makerus What problems are you facing on windows and how does this change solves it?

**Comment by makerus** [comment]
@gauravtiwari run command from README:

`PS path> foreman start
00:21:46 web.1       | started with pid 8820
00:21:46 webpacker.1 | started with pid 9956
00:21:46 webpacker.1 | yarn run v0.24.6
00:21:47 webpacker.1 | $ "path\node_modules\.bin\webpack-dev-server" --progress --color --config path/config/webpack/development.js
00:21:47 webpacker.1 | exited with code 0
00:21:47 system      | sending SIGKILL to all processes
00:21:47 system      | sending SIGKILL to web.1 at pid 8820
00:21:47 web.1       | exited with code 0`

OS: windows 10

Procfile:
`
#Run Webpacker
web: bundle exec rails s
webpacker: ruby bin/webpack-dev-server
`

**Comment by gauravtiwari** [comment]
Ahh I see. Have you tried just this without your `hack`?

```
web: bundle exec rails s
webpacker: ruby bin/webpack-dev-server
```

**Comment by javan** [comment]
> `00:21:47 webpacker.1 | $ "path\node_modules\.bin\webpack-dev-server"`

That `path\` stands out to me as a possible problem.

**Comment by makerus** [comment]
> Ahh I see. Have you tried just this without your hack?
@gauravtiwari, i tryed this methods before what write this "hack"

**Comment by makerus** [comment]
@javan, may be, may be

**Comment by gauravtiwari** [comment]
@makerus Have you seen this issue - https://github.com/rails/webpacker/issues/437?

**Comment by makerus** [comment]
@gauravtiwari, no, but check this solve, log:

webpacker.yml
```
dev_server:
    host: 127.0.0.1
    port: 8080
    https: false

```

Procfile:
```
web: bundle exec rails s
dev: ruby .\bin\webpack-dev-server
```

```
01:16:59 web.1  | started with pid 3132
01:16:59 dev.1  | started with pid 11844
01:17:00 dev.1  | yarn run v0.24.6
01:17:00 dev.1  | $ "path\node_modules\.bin\webpack-dev-server" --progress --color --config path/config/webpack/development.js
01:17:01 dev.1  | exited with code 0
01:17:01 system | sending SIGKILL to all processes
01:17:01 system | sending SIGKILL to web.1 at pid 3132
01:17:01 web.1  | exited with code 0
```

Don't solve this problem...

**Comment by gauravtiwari** [comment]
@makerus Could you try running binstub without foreman please - forgive me I don't know much about how things work on windows? `ruby .\bin\webpack-dev-server`

**Comment by makerus** [comment]
@gauravtiwari sry what long time don't repeat.

> Could you try running binstub without foreman
> ruby .\bin\webpack-dev-server

It's run successfuly, but with foreman don't run.

**Comment by gauravtiwari** [comment]
@makerus Looks like something wrong with foreman on windows then. Foreman works on Linux and OSX though. You might wanna open an issue on foreman repo 👍

**Pull request closed without merging**
