### PR TITLE
Update readme anchors

### PR DESCRIPTION
**Pull request by FireLemons**
#Resolved and #Watched under #Paths don't link to anything
image
and #additional-paths had no link
image

### CODE REVIEW

**Comment by aried3r** [comment]
Hey! I believe the ToC is generated using `doctoc` according to the comment above the ToC in the README.md.

If you run `npx doctoc --title "## Table of Contents" README.md` you should end up with the following, which also updates everything else:

```Markdown
- [Prerequisites](#prerequisites)
- [Features](#features)
  - [Optional support](#optional-support)
- [Installation](#installation)
  - [Usage](#usage)
    - [Server-Side Rendering (SSR)](#server-side-rendering-ssr)
  - [Development](#development)
  - [Webpack Configuration](#webpack-configuration)
  - [Integrations](#integrations)
    - [CoffeeScript](#coffeescript)
    - [TypeScript](#typescript)
    - [CSS](#css)
    - [Postcss](#postcss)
    - [Sass](#sass)
    - [Less](#less)
    - [Stylus](#stylus)
    - [React](#react)
    - [Other frameworks](#other-frameworks)
  - [Custom Rails environments](#custom-rails-environments)
  - [Upgrading](#upgrading)
- [Paths](#paths)
  - [Resolved](#resolved)
  - [Watched](#watched)
  - [Additional paths](#additional-paths)
- [Deployment](#deployment)
- [Troubleshooting](#troubleshooting)
- [Contributing](#contributing)
- [License](#license)
```

**Comment by FireLemons** [comment]
why are these still here
image

**Comment by aried3r** [comment]
@FireLemons, good catch! I accidentally copied the diff instead of the result. It of course should read:

```Markdown
- [Prerequisites](#prerequisites)
- [Features](#features)
  - [Optional support](#optional-support)
- [Installation](#installation)
  - [Usage](#usage)
    - [Server-Side Rendering (SSR)](#server-side-rendering-ssr)
  - [Development](#development)
  - [Webpack Configuration](#webpack-configuration)
  - [Integrations](#integrations)
    - [CoffeeScript](#coffeescript)
    - [TypeScript](#typescript)
    - [CSS](#css)
    - [Postcss](#postcss)
    - [Sass](#sass)
    - [Less](#less)
    - [Stylus](#stylus)
    - [React](#react)
    - [Other frameworks](#other-frameworks)
  - [Custom Rails environments](#custom-rails-environments)
  - [Upgrading](#upgrading)
- [Paths](#paths)
  - [Additional paths](#additional-paths)
- [Deployment](#deployment)
- [Troubleshooting](#troubleshooting)
- [Contributing](#contributing)
- [License](#license)
```

**Comment by FireLemons** [comment]
@aried3r thanks for showing me doctoc

**Pull request merged**
