### PR TITLE
add relative_url_root to webpacker config

### PR DESCRIPTION
**Pull request by ipmsteven**
This PR will set `WEBPACKER_RELATIVE_URL_ROOT` as `ActionController::Base.relative_url_root` which partially solve this issue https://github.com/rails/webpacker/issues/1106

would you mind taking a look? @gauravtiwari 
Thanks

### CODE REVIEW

**Comment by brunoOSI** [comment]
Please add this in, it is a bummer that you only can ship precompiled asset paths. It should allow some configuration!

**Comment by gauravtiwari** [comment]
Thanks @ipmsteven for this. Sorry for the delay. 
I think this requires a bit more wiring to function correctly like appending relative root to publicPath. Will take a look at this soon.

**Comment by ipmsteven** [comment]
Hi @gauravtiwari 

You are right, this PR only make `relative_url_root` available during webpack compile time.  A bit more wiring need to be done in webpacker level to construct `publicPath` that respect `relative_url_root`.
I am thinking we could start with it and delegate the plumbing work to the user of webpacker for now.

so with that being said above, If you agree with the proposal of adding `WEBPACKER_RELATIVE_URL_ROOT` to webpacker compile environment, 

we could either
Plan 1:
1. merge this PR that only ships `WEBPACKER_RELATIVE_URL_ROOT` first
2. have separate PR to do the wiring work as you mentioned above

OR

Plan 2: Have one PR handle both 1 and 2

I am fine with either one, what do you think? :)

**Comment by ipmsteven** [comment]
thanks! @gauravtiwari

**Pull request merged**
