### PR TITLE
Update Heroku instructions to include buildpack sequence

### PR DESCRIPTION
**Pull request by dpaola2**

### CODE REVIEW

**Comment by ytbryan** [comment]
Is there necessary? Heroku seems to have it installed by default, correct me if i'm wrong.

**Comment by dpaola2** [comment]
I was following the instructions on a (nearly) vanilla rails app and ran into #1282 . This was my issue. Just trying make sure others behind me don't hit the same (extremely frustrating) obstacle.

**Comment by p0wl** [comment]
We had to do this by hand as well.

**Comment by matthewd** [comment]
cc @hone

**Comment by joecorkerton** [comment]
I ran into the same problem, thanks for the fix. I also created an issue in the ruby buildpack repo as I believe that is where this should be fixed.

https://github.com/heroku/heroku-buildpack-ruby/issues/712

**Comment by sunnyrjuneja** [comment]
We also had to do this. It's also helpful to specify the version of node / yarn in package.json. I think it's worth mentioning in the PR.

**Comment by guilleiguaran** [comment]
Looks like this has been fixed already on the Heroku buildpack.

**Pull request closed without merging**
