### PR TITLE
Make public root path configurable

### PR DESCRIPTION
**Pull request by palkan**
Related to #1841 (https://github.com/rails/webpacker/issues/1841#issuecomment-449141454)

### CODE REVIEW

**Comment by gauravtiwari** [comment]
thanks @palkan

**Comment by ghaydarov** [comment]
👍

**Comment by justin808** [comment]
@gauravtiwari docs on this?

**Comment by palkan** [comment]
@justin808 See https://github.com/rails/webpacker/pull/1855

**Pull request merged**
