### PR TITLE
Support gem assets importing

### PR DESCRIPTION
**Pull request by rhyzx**
```
// app/javascript/packs/application.js
import 'rails-ujs'
import 'activestorage'
import 'turbolinks'
```

Related issues #956

### CODE REVIEW

**Comment by rossta** [comment]
Could you elaborate on the use case? Each of the examples you listed are available on NPM, so you could add them via `yard add <package>`, no?

**Comment by rhyzx** [comment]
@rossta This ensures that the gem and assets versions are consistent and they can be used in the same way as the sprockets.

**Comment by gauravtiwari** [comment]
@rhyzx You could use npm packages with sprockets now so I would say just install these via yarn and use them consistently everywhere (unless I am missing something).

**Comment by rossta** [comment]
@rhyzx We add selected `node_modules` directories to the Sprockets load path (as opposed to all node_modules which would add too many unneeded directories to the search space). Here's an example for `foundation-sites`, in which case, we're importing foundation javascript in Webpack and foundation scss files through Sprockets:

```ruby
# config/initializers/assets.rb
Rails.application.config do
  # ...

  config.assets.paths << Rails.root.join("node_modules", "foundation-sites", "scss")
end
```

**Comment by rhyzx** [comment]
@rossta thanks, it's also a viable option.

**Pull request closed without merging**
