### PR TITLE
Update postcss, postcss-import

### PR DESCRIPTION
**Pull request by aried3r**
Following the work of @pustovalov in #2749.

https://github.com/postcss/postcss-import/blob/13.0.0/CHANGELOG.md#1300--2020-10-20

Could I ask, what is the roadmap for webpacker 6? There are a lot of updates that we'd like to see released in there already.

### CODE REVIEW

**Comment by gauravtiwari** [comment]
thanks @aried3r Please see: #2757

**Comment by aried3r** [comment]
Thank you for the link! I was wondering, is there a chance to get a 5.3 with these dependency updates out before that?

**Comment by gauravtiwari** [comment]
Thanks @aried3r, good call. If no major changes involved, I will make a 5.3 release

**Comment by gauravtiwari** [comment]
Hi @aried3r Just took a look and feels like there are a few breaking changes in there so maybe makes sense to do a major release. Is webpacker pretty much webpack 5 ready?

**Pull request merged**
