### PR TITLE
Support to Yarn v2/berry for webpacker 5.x

### LINKED ISSUE #2888: Support for Yarn v2 in Webpacker 5.x
Hey @gauravtiwari ! 👋 

We are blocked to upgrade to Yarn v2 because the stable version of webpacker (currently v5.2.1) does not support Yarn v2.

The support for yarn berry is already done and merged in repo, by the PR https://github.com/rails/webpacker/pull/2799. It will be available in next major version of gem (6.x), but it can take a long time to be released, because of some structural changes and behaviors changes of webpack 5.

Is it possible to backport this PR to `5-x-stable` branch, and then release a minor version with this support to yarn v2? For this purpose, I've created a PR: https://github.com/rails/webpacker/pull/2889

Thanks a lot! 🤝 🎉

### PR DESCRIPTION
**Pull request by pedrofurtado**
@gauravtiwari 👋 

Closes #2888.

Clone of https://github.com/rails/webpacker/pull/2799 to provide support of Yarn v2 in 5.x versions of webpacker.

### CODE REVIEW

**Comment by pedrofurtado** [comment]
@gauravtiwari Could you help me? For any reason, when I execute `rails webpacker:compile`, with the code of this PR, appears the error `Compilation failed: -> command not found: webpack` 😢

**Comment by pedrofurtado** [comment]
@gauravtiwari It worked like a charm! 🎉 

PS: There are some errors in CI, but is not related to source code of PR, is related to some ruby version installed during build process 👍

**Comment by pedrofurtado** [comment]
@gauravtiwari Happy to see your review/suggestions on it 🎉 🥇

**Comment by pedrofurtado** [comment]
@gauravtiwari Happy to see your review/suggestions on it 🎉 🥇

**Comment by merobal** [comment]
Do you have any plan to release this? @pedrofurtado @gauravtiwari

**Comment by pedrofurtado** [comment]
Hi @merobal ! 👋  Yes, asap we will prepare a 5.x release 🎉

**Comment by jerrod** [comment]
@pedrofurtado any chance this updated release will happen reasonably soon?

**Comment by SampsonCrowley** [comment]
@pedrofurtado was this released? I'm still seeing this on latest 5.x (5.4.3) nearly 5 months later

Screenshot from 2021-09-27 00-54-27
Screenshot from 2021-09-27 00-56-32

**Comment by SampsonCrowley** [comment]
Nevermind, ignore me. I thought the version lock said `<= 3`

which why are we putting a *maximum* version on the new flags anyways? this is just going to keep needing to be rolled out every time, because when a new yarn version is released, the commands will revert to v1, instead of trying to assume compatibility with the most up-to-date api *first*

**Comment by SampsonCrowley** [comment]
And ignore me again, the issue above is with sprockets, not with the engine lock. running assets:precompile still attempts to trigger sprockets, even if sprockets is not enabled or installed on an app apparently

**Pull request merged**
