### PR TITLE
Fix README typo: s/boostrap/bootstrap/

### PR DESCRIPTION
**Pull request by freeatnet**

### CODE REVIEW

**Comment by freeatnet** [comment]
Additionally, the only way this code worked for me (on Rails 5.1.1, default `config/webpacker.yml`) was to have `@import '~bootstrap/dist/css/bootstrap'` rather than `@import '~bootstrap/dist/bootstrap.css'`. I know this issue has been mentioned [before](https://github.com/rails/webpacker/issues/489#issuecomment-307408324). Please let me know if this should be fixed (in this or another PR).

**Comment by gauravtiwari** [comment]
@freeatnet Yes please, if you could remove the extensions that would great - since we already have them in yml config file 👍

**Comment by kevgathuku** [comment]
Hey @freeatnet the path to the bootstrap CSS is also wrong. I had made a separate PR for that but since they're dealing with the same issue, we might as well fix it here.
It should be `bootstrap/dist/css/bootstrap.css` instead of `boostrap/dist/bootstrap.css`

**Comment by gauravtiwari** [comment]
Fixed in #514

**Pull request merged**
