### PR TITLE
Fix undefined method `watch' for Spring:Module

### PR DESCRIPTION
**Pull request by zernie**
This PR fixes `undefined method watch for Spring:Module` error.

### CODE REVIEW

**Comment by danielpowell4** [comment]
@zernie are you interested in getting the build to pass by appeasing the linter?

Would be appreciated!

**Comment by zernie** [comment]
@danielpowell4 yeah, sure. I've pushed the fix.

**Comment by danielpowell4** [comment]
@gauravtiwari though small this is a fairly decent sized issue with the `.pre.3`, at least for my app in development

Otherwise, I need to add the following patch inside somewhere like development.rb

```
require 'spring/watcher' if defined?(::Spring)
```

**Comment by gauravtiwari** [comment]
merged, thanks :)

**Pull request merged**
