### PR TITLE
Adding capistrano.md

### PR DESCRIPTION
**Pull request by majksner**
For common issues with Capistrano and Webpacker

### CODE REVIEW

**Comment by seuros** [comment]
This configuration is not webpacker specific. 

You should not link the public/pack folder, it generated at every deploy.

**Comment by majksner** [comment]
It should not be generated if files are not changed (JavaScript and CSS), right?

**Comment by majksner** [comment]
Here is the part of capistranp/rails plugin which makes sym link for public/assets

https://github.com/capistrano/rails/blob/0e14a506b63b17b7c2faeae4d083f569b0aa4920/lib/capistrano/tasks/assets.rake#L121

**Comment by seuros** [comment]
It will regenerate everything, unless you add a cache mechanism in webpack yourself.

**Comment by majksner** [comment]
I'm not sure if we're on the same page :blush:. My problem is that Webpacker was compiling assets on every deployment even if JS and CSS files are not changed (Why would Webpacker complile JS and CSS every deployment if no changes?). Before Webpacker, Asset pipeline didn't compile files if JS and CSS are not changed so I expect same behaviour with Webpacker.

**Comment by seuros** [comment]
I understood the goal. But did you test this approach in your deployment ?

Webpacker don't behave like sprockets, it will recompile everything even if nothing changed.

**Comment by majksner** [comment]
I did, it works perfectly. It's not true that will recompile everything, look at the compiler.rb, there are multiple things checking before it makes decision whether to recompile or not.

**Comment by seuros** [comment]
Maybe something wrong with my setup then. we will need feedback from other people that this method saves time.

**Comment by majksner** [comment]
I've added doc because it was suggested [here](https://github.com/rails/webpacker/issues/1903#issuecomment-456807668) by @gauravtiwari

**Comment by gauravtiwari** [comment]
@majksner I guess you are compiling locally and then deploy via Capistrano? (just to confirm)

**Comment by seuros** [comment]
@gauravtiwari  Capistrano will precompile in the remote servers from the checkouted code.  To compile locally, @majksner  will have to write a custom task.

**Comment by majksner** [comment]
@gauravtiwari I'm not doing anything locally, when I push code, CI runs Capistrano and all code is executed on the server.

**Comment by gauravtiwari** [comment]
@seuros Thanks :)

So, are you storing precompiled assets anywhere? I guess you would need to store them somewhere in order to use them in the later builds if nothing has changed, right?

**Comment by gauravtiwari** [comment]
For example, how circle CI cache or Heroku cache works.

**Comment by stevequinlan** [comment]
+1 for this tip, we knocked ~15 minutes off our deployment by adding public/packs to Capistrano's `:linked_dirs` setting.

**Comment by majksner** [comment]
@gauravtiwari I don't know your use case, but when running Capistrano from CI you don't have to cache anything since Capistrano will execute all your commands directly on server. So in my case gem files and the assets are stored on the server where code is deployed. My CI (GitLab CI) output is below in case you want to check it out.

Running with gitlab-runner 11.6.1 (8d829975)
  on gitlab-ce fc7866d0
Using Docker executor with image registry.acme.com/devops/deployment:2.6.0 ...
Pulling docker image registry.acme.com/devops/deployment:2.6.0 ...
Using docker image sha256:bf3bec67e470b235b8c0597ff5b191353886c2c5864ad8a4bc81ec0ddcae6e83 for registry.acme.com/devops/deployment:2.6.0 ...
Running on runner-fc7866d0-project-1-concurrent-0 via gitlab-ce...
Fetching changes...
Removing log/capistrano.log
HEAD is now at a6916bd Merge branch 'develop' into staging
From https://git.acme.com/acme/acme
   9b1da43..dc65206  develop    -> origin/develop
   a6916bd..c9f45b9  staging    -> origin/staging
Checking out c9f45b9c as staging...
Skipping Git submodules setup
$ eval $(ssh-agent -s)
Agent pid 11
$ ssh-add <(echo "$SSH_PRIVATE_KEY")
Identity added: /dev/fd/63 (/dev/fd/63)
$ mkdir -p ~/.ssh
$ [[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
$ cap staging deploy
rvm 1.29.7 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
ruby-2.6.0
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-linux]
00:00 git:wrapper
      01 mkdir -p /tmp
    ✔ 01 deploy@staging.acme.com 0.052s
      Uploading /tmp/git-ssh-acme-staging-.sh 100.0%
      02 chmod 700 /tmp/git-ssh-acme-staging-.sh
    ✔ 02 deploy@staging.acme.com 0.047s
00:00 git:check
      01 git ls-remote git@git.acme.com:acme/acme.git HEAD
      01 dc652062c8629ee6880b842c31af172e758333bc	HEAD
    ✔ 01 deploy@staging.acme.com 1.125s
00:01 deploy:check:directories
      01 mkdir -p /var/www/acme/shared /var/www/acme/releases
    ✔ 01 deploy@staging.acme.com 0.048s
00:01 deploy:check:linked_dirs
      01 mkdir -p /var/www/acme/shared/log /var/www/acme/shared/tmp/pids /var/www/acme/shared/tmp/cache /var/www/acme/shared/tmp/sockets /var/www/acme/shared/public/packs /var/www/acme/shared/.bundle /var/www/acme/shared/public/assets
    ✔ 01 deploy@staging.acme.com 0.051s
00:01 deploy:check:make_linked_dirs
      01 mkdir -p /var/www/acme/shared/config /var/www/acme/shared
    ✔ 01 deploy@staging.acme.com 0.049s
00:01 sidekiq:quiet
      01 systemctl --user reload sidekiq-staging.service
    ✔ 01 deploy@staging.acme.com 0.059s
00:01 git:clone
      The repository mirror is at /var/www/acme/repo
00:01 git:update
      01 git remote set-url origin git@git.acme.com:acme/acme.git
    ✔ 01 deploy@staging.acme.com 0.050s
      02 git remote update --prune
      02 Fetching origin
      02 From git.acme.com:acme/acme
      02  * [new ref]         refs/environments/staging/deployments/503 -> refs/environments/staging/deployments/503
      02    9b1da43..dc65206  develop    -> develop
      02    a6916bd..c9f45b9  staging    -> staging
    ✔ 02 deploy@staging.acme.com 1.360s
00:03 git:create_release
      01 mkdir -p /var/www/acme/releases/20190123153529
    ✔ 01 deploy@staging.acme.com 0.050s
      02 git archive staging | /usr/bin/env tar -x -f - -C /var/www/acme/releases/20190123153529
    ✔ 02 deploy@staging.acme.com 0.115s
00:03 deploy:set_current_revision
      01 echo "c9f45b9c3f99452eb78c563269f105c71043581b" > REVISION
    ✔ 01 deploy@staging.acme.com 0.048s
00:03 deploy:symlink:linked_files
      01 mkdir -p /var/www/acme/releases/20190123153529/config /var/www/acme/releases/20190123153529
    ✔ 01 deploy@staging.acme.com 0.048s
      02 ln -s /var/www/acme/shared/config/master.key /var/www/acme/releases/20190123153529/config/master.key
    ✔ 02 deploy@staging.acme.com 0.048s
      03 ln -s /var/www/acme/shared/.env /var/www/acme/releases/20190123153529/.env
    ✔ 03 deploy@staging.acme.com 0.049s
      04 ln -s /var/www/acme/shared/gcloud.json /var/www/acme/releases/20190123153529/gcloud.json
    ✔ 04 deploy@staging.acme.com 0.049s
00:04 deploy:symlink:linked_dirs
      01 mkdir -p /var/www/acme/releases/20190123153529 /var/www/acme/releases/20190123153529/tmp /var/www/acme/releases/20190123153529/public
    ✔ 01 deploy@staging.acme.com 0.046s
      02 rm -rf /var/www/acme/releases/20190123153529/log
    ✔ 02 deploy@staging.acme.com 0.050s
      03 ln -s /var/www/acme/shared/log /var/www/acme/releases/20190123153529/log
    ✔ 03 deploy@staging.acme.com 0.049s
      04 ln -s /var/www/acme/shared/tmp/pids /var/www/acme/releases/20190123153529/tmp/pids
    ✔ 04 deploy@staging.acme.com 0.048s
      05 ln -s /var/www/acme/shared/tmp/cache /var/www/acme/releases/20190123153529/tmp/cache
    ✔ 05 deploy@staging.acme.com 0.048s
      06 ln -s /var/www/acme/shared/tmp/sockets /var/www/acme/releases/20190123153529/tmp/sockets
    ✔ 06 deploy@staging.acme.com 0.048s
      07 ln -s /var/www/acme/shared/public/packs /var/www/acme/releases/20190123153529/public/packs
    ✔ 07 deploy@staging.acme.com 0.048s
      08 ln -s /var/www/acme/shared/.bundle /var/www/acme/releases/20190123153529/.bundle
    ✔ 08 deploy@staging.acme.com 0.049s
      09 ln -s /var/www/acme/shared/public/assets /var/www/acme/releases/20190123153529/public/assets
    ✔ 09 deploy@staging.acme.com 0.048s
00:06 bundler:install
      The Gemfile's dependencies are satisfied, skipping installation
00:06 deploy:assets:precompile
      01 ~/.rvm/bin/rvm default do bundle exec rake assets:precompile
      01 yarn install v1.12.3
      01 [1/4] Resolving packages...
      01 [2/4] Fetching packages...
      01 info fsevents@1.2.4: The platform "linux" is incompatible with this module.
      01 info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
      01 [3/4] Linking dependencies...
      01 warning " > @babel/preset-react@7.0.0" has unmet peer dependency "@babel/core@^7.0.0-0".
      01 warning "@babel/preset-react > @babel/plugin-transform-react-display-name@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
      01 warning "@babel/preset-react > @babel/plugin-transform-react-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
      01 warning "@babel/preset-react > @babel/plugin-transform-react-jsx-self@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
      01 warning "@babel/preset-react > @babel/plugin-transform-react-jsx-source@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
      01 warning "@babel/preset-react > @babel/plugin-transform-react-jsx > @babel/plugin-syntax-jsx@7.2.0" has unmet peer dependency "@babel/core@^7.0.0-0".
      01 warning "@rails/webpacker > pnp-webpack-plugin > ts-pnp@1.0.0" has unmet peer dependency "typescript@*".
      01 warning " > bootstrap@4.2.1" has unmet peer dependency "popper.js@^1.14.6".
      01 warning "shapeviewer > @wildpeaks/three-webpack-plugin@2.0.0" has unmet peer dependency "webpack@*".
      01 warning " > webpack-dev-server@3.1.10" has unmet peer dependency "webpack@^4.0.0".
      01 warning "webpack-dev-server > webpack-dev-middleware@3.4.0" has unmet peer dependency "webpack@^4.0.0".
      01 [4/4] Building fresh packages...
      01 Done in 13.38s.
    ✔ 01 deploy@staging.acme.com 20.828s
00:27 deploy:assets:backup_manifest
      01 mkdir -p /var/www/acme/releases/20190123153529/assets_manifest_backup
    ✔ 01 deploy@staging.acme.com 0.051s
      02 cp public/packs/manifest.json /var/www/acme/releases/20190123153529/assets_manifest_backup
    ✔ 02 deploy@staging.acme.com 0.047s
00:27 deploy:migrate
      [deploy:migrate] Run `rake db:migrate`
00:27 deploy:migrating
      01 ~/.rvm/bin/rvm default do bundle exec rake db:migrate
      01 Migrating staging tenant
    ✔ 01 deploy@staging.acme.com 4.795s
00:32 sidekiq:stop
      01 systemctl --user stop sidekiq-staging.service
    ✔ 01 deploy@staging.acme.com 0.610s
00:32 deploy:symlink:release
      01 ln -s /var/www/acme/releases/20190123153529 /var/www/acme/releases/current
    ✔ 01 deploy@staging.acme.com 0.049s
      02 mv /var/www/acme/releases/current /var/www/acme
    ✔ 02 deploy@staging.acme.com 0.048s
00:32 sidekiq:start
      01 systemctl --user start sidekiq-staging.service
    ✔ 01 deploy@staging.acme.com 0.053s
00:33 deploy:cleanup
      Keeping 10 of 11 deployed releases on staging.acme.com
      01 rm -rf /var/www/acme/releases/20190123131131
    ✔ 01 deploy@staging.acme.com 1.223s
00:34 deploy:notify
      01 curl https://sentry.io/api/0/organizations/acme/releases/c9f45b9c3f99452eb78c563269f105c71043581b/deploys/ -X POST -H "Content-Type: application/json" -d '{"environment": staging}' >/dev/null 2>&1
    ✔ 01 deploy@staging.acme.com 0.463s
00:35 deploy:log_revision
      01 echo "Branch staging (at c9f45b9c3f99452eb78c563269f105c71043581b) deployed as release 20190123153529 by " >> /var/www/acme/revisions.log
    ✔ 01 deploy@staging.acme.com 0.055s
00:35 puma:restart
      01 ~/.rvm/bin/rvm default do bundle exec pumactl -S /var/www/acme/shared/tmp/pids/puma.state -F /var/www/acme/shared/puma.rb restart
      01 Command restart sent success
    ✔ 01 deploy@staging.acme.com 2.750s
Job succeeded

**Comment by gauravtiwari** [comment]
Thanks @majksner No, I was just being curious and wanted to understand how Capistrano works. I guess you wanna do this for `node_modules` too similar to gems so it's cached between releases: https://github.com/capistrano/npm/issues/7

```
set :copy_files, ['node_modules']
before 'assets:precompile'
```

or 

```
# Default value for linked_dirs is []
linked_dirs = Set.new(fetch(:linked_dirs, [])) # https://github.com/capistrano/rails/issues/52
linked_dirs.merge(%w{node_modules})
set :linked_dirs, linked_dirs.to_a
```

Can document this if it works for you?

**Comment by majksner** [comment]
@gauravtiwari It works! down to 1s from 13s. 

`ruby
append :linked_dirs, "log", "tmp/pids", "tmp/cache", "tmp/sockets", "public/packs", ".bundle", "node_modules"
`

**Comment by gauravtiwari** [comment]
Awesome, will merge this now, thanks for your help :)

**Comment by majksner** [comment]
@gauravtiwari No problem, if someone creates issue with Capistrano feel free to mention me and I'll look into it.

**Comment by gauravtiwari** [comment]
Thanks, @majksner, really appreciate it. I just realised,  we should have put the Capistrano doc here: https://github.com/rails/webpacker/blob/master/docs/deployment.md

If you get chance can you make a pr, remove capistrano.md and then move it to deployment.md

**Pull request merged**
