### PR TITLE
Removing javascript_packs_with_chunks_tag

### PR DESCRIPTION
**Pull request by guillaumebriday**
Since chunks are enabled by default, I think we should have only one helper to manage tags

### CODE REVIEW

**Comment by gauravtiwari** [comment]
Thanks @guillaumebriday 

Thinking if we merge the functionality of split chunks and pack together into one pack tag like discussed in the basecamp channel. I guess that gives much easier migration path to everyone, which supports both single and multiple although single won't be the case since we support split chunks by default but just in case.

```rb
javascript_pack_tag
```

What do you think?

**Comment by rossta** [comment]
@guillaumebriday Thanks for opening this PR! I like having one tag that will work whether splitChunks is enabled or not. I hope this will mean a lot less friction for the upgrade and for first-time Webpacker users.

**Comment by guillaumebriday** [comment]
What is for you the best way to detect is chunks are enabled? 

Looking for entrypoints in the manifest?
Looking at the Webpack configuration `splitChunks` key?

@gauravtiwari @rossta

**Comment by rossta** [comment]
@guillaumebriday If I understand your question correctly, I was thinking, as a start, that Rails doesn't need to know if splitChunks are enabled since I believe the manifest structure for will be the same in either case, i.e. `entrypoints.[entrypoint name].assets.[mime type]` always returns an array.

##### With splitChunks:
```js
{
  "application.js": "/packs/js/application-8ede64f597a359e638bc.js",
  "entrypoints": {
    "application": {
      "assets": {
        "js": [
          "/packs/js/runtime-d987b1110ba1ea8e32da.js",
          "/packs/js/vendors-node_modules_rails_activestorage_app_assets_javascripts_activestorage_js-node_modules-8bd44b-231ec25f0e7dc52f4f1b.js",
          "/packs/js/application-8ede64f597a359e638bc.js"
        ]
      }
    }
  },
  "js/application-8ede64f597a359e638bc.js.map": "/packs/js/application-8ede64f597a359e638bc.js.map",
  "js/runtime-d987b1110ba1ea8e32da.js.map": "/packs/js/runtime-d987b1110ba1ea8e32da.js.map",
  "js/vendors-node_modules_rails_activestorage_app_assets_javascripts_activestorage_js-node_modules-8bd44b-231ec25f0e7dc52f4f1b.js": "/packs/js/vendors-node_modules_rails_activestorage_app_assets_javascripts_activestorage_js-node_modules-8bd44b-231ec25f0e7dc52f4f1b.js",
  "js/vendors-node_modules_rails_activestorage_app_assets_javascripts_activestorage_js-node_modules-8bd44b-231ec25f0e7dc52f4f1b.js.map": "/packs/js/vendors-node_modules_rails_activestorage_app_assets_javascripts_activestorage_js-node_modules-8bd44b-231ec25f0e7dc52f4f1b.js.map",
  "runtime.js": "/packs/js/runtime-d987b1110ba1ea8e32da.js"
}
```

##### Without splitChunks, e.g. `delete webpackConfig.optimization`:
```js
{
  "application.js": "/packs/js/application-09f52628f5c8b3752f2b.js",
  "entrypoints": {
    "application": {
      "assets": {
        "js": [
          "/packs/js/application-09f52628f5c8b3752f2b.js"
        ]
      }
    }
  },
  "js/application-09f52628f5c8b3752f2b.js.map": "/packs/js/application-09f52628f5c8b3752f2b.js.map"
}
``

So the code as you have it should work for both.

**Comment by gauravtiwari** [comment]
Sorry this completely slipped off my radar @guillaumebriday 

Thanks @rossta Yes exactly 👍

**Comment by gauravtiwari** [comment]
@guillaumebriday Is this PR good to go?

**Comment by guillaumebriday** [comment]
thanks @rossta! 

And I think we're good to go @gauravtiwari

**Comment by gauravtiwari** [comment]
awesome work 🍰

**Comment by guillaumebriday** [comment]
Thanks @gauravtiwari

**Comment by rossta** [comment]
@guillaumebriday Yes, nice work!

**Comment by guillaumebriday** [comment]
Thanks @rossta

**Pull request merged**
