### PR TITLE
Replace postcss-cssnext with postcss-preset-env

### PR DESCRIPTION
**Pull request by ojab**
postcss-cssnext is deprecated (see https://github.com/MoOx/postcss-cssnext/issues/445) and postcss-preset-env should be used instead.

`yarn upgrade` is done in the first commit to minimize lockfile diff due to actual package change.

### CODE REVIEW

**Comment by gauravtiwari** [comment]
@ojab Thanks for this but could you please remove the commit related to `yarn upgrade`. Is that necessary? or we can do yarn upgrade in a separate PR with package.json update.

**Comment by ojab** [comment]
done

**Comment by renchap** [comment]
`cssnext` deprecation blog post: https://moox.io/blog/deprecating-cssnext/

**Comment by ojab** [comment]
`autoprefixer` is actually included into `postcss-present-env`, linked post was corrected. So no breaking changes expected.

**Comment by gauravtiwari** [comment]
thanks @ojab

**Comment by jaredbeck** [comment]
Can this be easily backported to v3?

**Pull request merged**
