### PR TITLE
Pass the command line arguments to the webpack-dev-server module (#2000)

### PR DESCRIPTION
**Pull request by marisveide**
Fixes the issue: https://github.com/rails/webpacker/issues/2000

### CODE REVIEW

**Comment by gauravtiwari** [comment]
Thanks @marisveide 

The reason for not allowing config options in dev server runner is because of sync problem in options like `host` and `port` etc since they are used on both Ruby and JS side and it's hard to keep them in sync if we have too many sources to set them up (plus it might be confusing for some people). 

At the moment, Webpacker supports `.yml` file and `environment variables`

Perhaps, we can allow all other options except certain like `host` and `port`. This may need some testing.

**Comment by marisveide** [comment]
@gauravtiwari - so are you saying this Pull Request will not get rejected?

This change really helped us set up our development environments properly. And looks like it helped others too already who need to pass the file names from the command line...

**Comment by nicklozon** [comment]
@gauravtiwari using ```webpacker.yml``` and environment variables is okay, but it does make the configuration less flexible because @marisveide will need to be copying his key and cert into the yaml file whenever it changes.

Another issue I ran into is the webpack-dev-server ```https``` configuration isn't a boolean, but webpacker's reverse proxy won't use https unless that configuration (or the environment variable) is explicitly set to true, and if it is set to true then the key and cert files will never make it to the webpack-dev-server configuration.

Here is my comment about it: https://github.com/rails/webpacker/issues/2000#issuecomment-485312873

**Comment by dj0nes** [comment]
Ran into this issue in development.

@gauravtiwari - If we filter out `host` and `port` from the argument list, would we be closer to getting this feature merged?

**Comment by marisveide** [comment]
Yeah, it would be great to merge this... otherwise we are sitting on our fork, and would be glad to not have to maintain the forked version just because we need to pass the SSL certificate params.

**Comment by marisveide** [comment]
Hi!

What do I have to do to get this PR merged?

Thanks!

Maris

**Comment by gauravtiwari** [comment]
@marisveide and everyone, apologies for long silence 🙏 

One solution: 

If you can filter out the options supported in webpacker.yml inside dev server then I am happy to review. Perhaps, if one supplies the options already supported in `webpacker.yml`, we can display a friendly warning i.e. "Please set the option in `webpacker.yml` instead"

The reason to do this is because, we use some options on both node and ruby side (host, port etc.) and if there are multiple ways to declare, it will cause confusion and issues. 

---

I know this still doesn't solve the whole problem, for example colleagues working together want to change these options on runtime without committing. Maybe let's try to figure out a better solution, together. 

Simply, allowing options to dev server would cause other problems.

**Pull request closed without merging**
