### PR TITLE
change lodash.keyBy to pure javascript

### PR DESCRIPTION
**Pull request by Nitrino**

### CODE REVIEW

**Comment by dhh** [comment]
Sweet! We can kill lodash from the install/template.rb definition then too.

**Comment by Nitrino** [comment]
lodash is still used for _.merge. @guilleiguaran solves this.

**Comment by dhh** [comment]
Oh right.

**Comment by dhh** [comment]
Let's nix the ;'s btw.

**Comment by Nitrino** [comment]
Do you plan to use ES6(babel) by default? 
In ES6, instead of `lodash.merge` can use the native method `Object.assign`

**Comment by dhh** [comment]
Yeah, would actually be nice to have that setup for the config files too.
Please to investigate!

**Comment by nathanmarks** [comment]
`lodash.merge` !== `Object.assign`

`_.merge` does a deep merge, `Object.assign` is a shallow merge.

I'd recommend sticking with a deep merge for webpack configuration.

**Comment by nathanmarks** [comment]
Also, you don't need babel to use `Object.assign`, that's dependent on the node runtime being used when it comes to this config.

**Comment by Nitrino** [comment]
@nathanmarks Oh sorry, you're right, `Object.assign` only does a shallow merge. 
It would be better to use [webpack-merge](https://www.npmjs.com/package/webpack-merge)

**Comment by koenpunt** [comment]
Or use https://www.npmjs.com/package/deepmerge for merging.

**Pull request merged**
