### PR TITLE
upgrade js-yaml to version 3.13.1

### PR DESCRIPTION
**Pull request by GabrielFn**

### CODE REVIEW

**Comment by jakeNiemiec** [comment]
Any idea why the tests fail?

**Comment by SauloSilva** [comment]
@GabrielFn maybe bundle version.

Try:

```
gem install bundler -v '~> 2.0.0'
bundle
```

**Comment by GabrielFn** [comment]
The problem seems to be in the base branch 3-x-stable

https://travis-ci.org/rails/webpacker/branches

**Comment by aried3r** [comment]
Hijacking this a bit, I see a few issues opened for webpacker 3 and PRs that target 3.x. Is webpacker 3 even officially maintained anymore? /cc @jakeNiemiec

**Comment by jakeNiemiec** [comment]
> Is webpacker 3 even officially maintained anymore?

[May 2018 was the last release](url)

To be honest, I don't think [this is a problem](https://vuln.whitesourcesoftware.com/vulnerability/WS-2019-0063/) for webpacker, I can't think of how you would get malicious code in your `webpacker.yml` file to warrant the concern here.

**Pull request closed without merging**
