### PR TITLE
Always check files recompilation by content

### LINKED ISSUE #1439: Recompile only modified assets in production
Working in dev is great. Webpack recompiles and dev-server send to browser only changed files.

But in production it occurs to recompile ALL files. And it WAY TOO LONG.

Is there any method to recompile ONLY CHANGED files in production?

### PR DESCRIPTION
**Pull request by mdesantis**
Fix #1439

### CODE REVIEW

**Comment by mdesantis** [comment]
@gauravtiwari I thought about that too but I'm worried about CI: it's unlikely that you run tests under production environment. What about doing `CI env var check || env.production?`?

Also, an alternative fix could be just documenting the CI env var in the readme (and maybe renaming that; I don't think it's descriptive enough); developers might just be confused by the fact that this behaviour isn't written loud and clear

**Comment by latortuga** [comment]
As someone who is not super familiar with webpacker internals, forgive me if this is a dumb question. Is this codepath even used in development? My impression is that this feature is for when assets are precompiled, which doesn't happen in development mode.

**Comment by mdesantis** [comment]
@latortuga (not a Webpacker expert neither) but you can precompile assets even in development if for some reason you don't want to use `webpack-dev-server`, although it isn't very common; and anyway you precompile them in test mode, if we are considering `development` as `non-produciton`

**Comment by swrobel** [comment]
> I thought about that too but I'm worried about CI: it's unlikely that you run tests under production environment. What about doing `CI env var check || env.production?`?

Please see @gauravtiwari's [comment here](https://github.com/rails/webpacker/issues/1611#issuecomment-417745121) for an example of what he means. Production & Test (or any env other than Development) would use the file hash method.

**Comment by jpickwell** [comment]
Is there a reason why the results of `watched_files_digest` isn't memoized? The function gets called once by `stale?` and again by `record_compilation_digest` (if `stale?` returns `true`) when calling `compile`.

**Comment by swrobel** [comment]
@jpickwell I raised this with my [earlier PR](https://github.com/rails/webpacker/pull/1522#issuecomment-394158222) and got the 👍 but didn't get around to implementing it.

**Comment by gauravtiwari** [comment]
Thanks everyone 🙏 

Lets use `mtime` in development and file hash for other environments, where most likely we would be precompiling assets.

**Why in development?**

Mainly because, Webpacker ships with this "naive" on-demand compiler, which works well for simple cases and we don't want to slow it down, even if it's tiny by using file hash. If I am not missing anything, I think `mtime` should work fine there? 

----
But as I wrote the above paragraph, I realised for simple cases using file hash wouldn't be slow either. So, perhaps just use file hash for everything to keep things simple?

**Comment by gauravtiwari** [comment]
Thanks @mdesantis :)

**Comment by kjleitz** [comment]
Any chance this will be put into 3.x? This fix would _really_ help our deployment process out. Deployment went from 3-4 minutes to ~15 minutes for us. It's a big pain.

**Comment by latortuga** [comment]
@kjleitz looks like this got released on March 6, 2019: https://github.com/rails/webpacker/commit/8c25c092dede858d8c5ba2aa708e0134216dc8b0

:tada:

**Pull request merged**
