### PR TITLE
Allow skipping webpacker compile when running assets:precompile

### PR DESCRIPTION
**Pull request by gauravtiwari**
Fixes: https://github.com/rails/webpacker/issues/967 and https://github.com/rails/webpacker/issues/811

### CODE REVIEW

**Comment by javan** [comment]
How about inverting it? `WEBPACKER=false rails assets:precompile`

**Comment by gauravtiwari** [comment]
Ahh yes, makes sense. Will push an update.

**Comment by gauravtiwari** [comment]
Although not sure, if just using `WEBPACKER` as env variable is fine. May be `WEBPACKER_PRECOMPILE`

**Comment by javan** [comment]
Could the issues referenced above just omit `webpacker` from their `Gemfile` using an env var of their choosing?

```ruby
# Gemfile
gem 'webpacker', '~> 3.0' unless ENV['WORKER_APP']
```

**Comment by javan** [comment]
I imagine that both of those issues would benefit from compiling assets on a single server and then `rsync`ing them to the rest. See https://github.com/rails/webpacker/issues/618#issuecomment-322053127 and https://github.com/rails/webpacker/issues/618#issuecomment-322062852.

**Comment by gauravtiwari** [comment]
> Could the issues referenced above just omit webpacker from their Gemfile using an env var of their choosing?

Yeah that would work but I guess this solution might produce some edge cases - like app has some code related to webpacker but the Gem isn't installed for that environment and build is failing.

> I imagine that both of those issues would benefit from compiling assets on a single server and then rsyncing them to the rest. See #618 (comment) and #618 (comment).

Yep but I think having an option to skip enhancement would be better, in case folks wants to have more control over how they deploy their apps. 

Perhaps, in future we can totally ditch enhancements and just allow invoking `webpacker:compile` during deployment. For Heroku, I guess this can be inside ruby buildback to detect if webpacker (which it does anyway) is present run that hook like `assets:precompile`

For other deployments, like capistrano this can be easily added in deployment script. 

What do you think?

**Comment by javan** [comment]
One more idea, and I'm not sure how to do this with rake, but we could alias the original `assets:precompile` task before enhancing it as `assets:precompile:without_webpacker` or something.

**Comment by gauravtiwari** [comment]
Yeah, great idea 👍  although it seems since rake lazily loads all tasks, after boot the alias task is enhanced too

**Pull request merged**
