### PR TITLE
Update dependencies in 5.x version

### PR DESCRIPTION
**Pull request by anark**
While we are waiting for the v6 version of webpacker it would be great to have a 5.x version fo webpacker that includes minor dependency updates.

This PR simply adds a minor version update on the 5.x dependencies.  Noted in the following issues.
https://github.com/rails/webpacker/issues/2974
https://github.com/rails/webpacker/issues/2969
https://github.com/rails/webpacker/issues/2959

### CODE REVIEW

**Comment by anark** [comment]
This is still a work in progress.  Doesn't look like webpacker 5.x can work with webpack-asset-manifest at this version.  Help appreciated.

**Comment by vinceve** [comment]
@anark are there tests for webpack-asset-manifest? Because it seems everything is working. I'm trying to understand what still needs to be done. :)

**Comment by anark** [comment]
@vinceve, I just noticed issues when I tried to use this in my project, however that could have had to do with how I built it.

Not really sure how to continue.  Ideally this would just be dismissed and a stable version fo 6.0 would be available and we could move forward on 6.0.  

If this was to be merged it would just require someone able to try it out and make sure it still works as expected

**Comment by victorlcampos** [comment]
Hi @anark,
How can I test on my project?

Can you help me with this?

**Comment by anark** [comment]
@victorlcampos it depends on what you are using to manage your dependencies(npm or yarn).

You should be able to either clone/download my fork and link to it locally or link to the github repo via yarn/npm.

https://classic.yarnpkg.com/en/docs/cli/add/.

Not sure if there is another build step needed.  Would have to ask someone else for help as I didn't get very far trying to use this, just updated the dependencies.

Ideally this wont be needed and v6 will be released and usable shortly and we can all move on to that.

**Comment by victorlcampos** [comment]
I'm using yarn, tomorrow I will try if everything is good.

**Comment by tsmartt** [comment]
> I'm using yarn, tomorrow I will try if everything is good.

How did it go?

**Comment by victorlcampos** [comment]
Hi @tsmartt,
I confess that I didn't got how upgrate to use anark version =/

**Comment by gauravtiwari** [comment]
Hi All, Just released 5.2.2 version with updated dependencies and removed node-sass: https://github.com/rails/webpacker/tree/5-x-stable

**Pull request closed without merging**
