### PR TITLE
Added support for rest/spread properties

### PR DESCRIPTION
**Pull request by tomprats**
Solves issue https://github.com/rails/webpacker/issues/457

### CODE REVIEW

**Comment by gauravtiwari** [comment]
Awesome! Thanks @tomprats 🍰  👍

**Comment by heeton** [comment]
Thanks for adding this. When will this be included in a new gem release?

**Comment by gauravtiwari** [comment]
@heeton Will publish a new version next week - a few PR's pending and need to push some updates for Webpack 3.0

**Comment by heeton** [comment]
👍 Thanks

**Pull request merged**
