### PR TITLE
Exit before precompile task if yarn:install or webpacker:yarn_install install fails

### PR DESCRIPTION
**Pull request by juliantrueflynn**
Solving problem for issue: #2185 

**How to test PR**:
1. Turn off internet connection
2. Run `rake assets:precompile`
3. Should now exit out before `Compiling...` (which current behavior is it still compiles)

**Please note**:
- This seems hacky, but after going at this for a bit it seemed to be only solution that didn't pollute `webpacker` Rake task scope, easiest to read, and least interference with current code base.
- If anyone has any idea on how to test this feature I'm all ears.

### CODE REVIEW

**Comment by gauravtiwari** [comment]
Hi @juliantrueflynn Thanks for this. Let's make a pull request at `rails/rails` to update `yarn:install` task but for now could you please use this style?

https://github.com/rails/webpacker/blob/48166da4ff156105bf7b153b1592db047705b0ea/lib/tasks/webpacker/compile.rake#L46

```rb
if Rake::Task.task_defined?("yarn:install")
    do_the_enhancing
  else
   # this is mainly for pre-5.x era
    Rake::Task.define_task("yarn:install" => task_definition)
end
```

**Comment by juliantrueflynn** [comment]
@gauravtiwari you got it. I will make PR later today and cc you. Will also update this PR later today with that style.

**Comment by juliantrueflynn** [comment]
I made PR to Rails. Also small note @gauravtiwari but I had no idea why I kept getting the error "Don't know how to build task 'some task name here' (See the list of available tasks with `rake --tasks`)"

Your suggested edit made me realize it was probably because I had Rake::Task in global scope and not abstracted to a method. Is that logic correct? If you don't have time to answer it's fine.

    # would give "don't know how to build task" error
    if Rake::Task.task_defined?("yarn:install")
        Rake::Task["yarn:install"].enhance { ...some code }
    end

    # would NOT give "don't know how to build task" error
    if Rake::Task.task_defined?("yarn:install")
       rake_task_abstracted_to_method
    end

**Comment by gauravtiwari** [comment]
Thanks @juliantrueflynn Looks great to me 👍

**Comment by samandmoore** [comment]
Any chance of getting this into a release any time soon? I'd love to get this fix into a few of my apps. 🙏

**Comment by juliantrueflynn** [comment]
@samandmoore Here's a quickfix for you so you don't have to wait:

```
namespace :webpacker do
  desc "Custom. Support for older Rails versions. Install all JavaScript dependencies as specified via Yarn"
  task :yarn_install do
    Rake::Task["wepacker:yarn_install"].enhance do
      exit(1) unless $?.success?
    end
  end
end
```

**Comment by jaredbeck** [comment]
Rails' `assets:precompile` now respects the exit code of `yarn install`, as of https://github.com/rails/rails/pull/36852

**Pull request merged**
