### PR TITLE
Upgrade Node Js  package 

### PR DESCRIPTION
**Pull request by smondal**
Upgrade Node Js packages with latest version

### CODE REVIEW

**Comment by jakeNiemiec** [comment]
For example, `css-loader` is one of the largest problems on that list since the acceptable config structure changed.

**Comment by smondal** [comment]
Thanks @jakeNiemiec for your reply. I will be working on dependencies upgrade. I have updated the webpacker version. But is their any way I can find all of the error which we need to fix after dependencies upgrade?  I found few tase cases is written under utils. Is this sufficient to find all the error after dependencies upgrade?

**Comment by jakeNiemiec** [comment]
Here is one example for the `css-loader`:  https://github.com/rails/webpacker/issues/2162#issuecomment-508827256. You can see that `getLocalIdent` was moved to `module.getLocalIdent` as a breaking change.

In this case, you would need to modify the structure that webpacker expects according to the breaking changes from `css-loader`: https://github.com/webpack-contrib/css-loader/blob/master/CHANGELOG.md#breaking-changes

Here is the webpacker file that you would need to change:

https://github.com/rails/webpacker/blob/41d79c96187154b5485289e8c3c42428dd819bfc/package/utils/get_style_rule.js#L18-L27

I don't think the tests currently cover this.

**Comment by smondal** [comment]
Thanks @jakeNiemiec, Still now we found, its issue with css-loader. After fixing  this issue "getLocalIdent was moved to module. getLocalIdent as a breaking change", compile was working fine for Vue JS.
But I will review other package's CHANGELOG. If there are any relevant changes I will update this.

**Comment by smondal** [comment]
Hi @jakeNiemiec  I see there is "babel-preset" is internally using '@babel/plugin-transform-destructuring', Still we are include this plugin inside "babel.config.js". do we really need this to include.

https://github.com/rails/webpacker/blob/master/lib/install/config/babel.config.js#L43

https://github.com/babel/babel/blob/eb54adb75589ef82041ad23cdfcb3168a52317a7/packages/babel-preset-env/package.json#L29

Can you please help me on this?

**Comment by jakeNiemiec** [comment]
You can read about how the plugins work here: https://babeljs.io/docs/en/options#plugins

That file dictates which plugins (_already listed in `package.json`_) are applied to our webpack build during the babel step. You can read more about that here: https://babeljs.io/docs/en/configuration

**Comment by smondal** [comment]
@jakeNiemiec My point was that we should removed '@babel/plugin-transform-destructuring' from "babel.config.js". 
https://github.com/rails/webpacker/blob/master/lib/install/config/babel.config.js#L43

**Pull request closed without merging**
