### PR TITLE
Remove VueLoaderPlugin and yarn add vue-loader:14.2.2

### PR DESCRIPTION
**Pull request by ytbryan**
This is for webpacker 4. Related to https://github.com/rails/webpacker/issues/1453

Tested on localhost and it works. cc @gauravtiwari

### CODE REVIEW

**Comment by gauravtiwari** [comment]
@ytbryan Shouldn't we be using 15.0.0 instead? https://github.com/vuejs/vue-loader/releases & https://vue-loader.vuejs.org/migrating.html

**Comment by ytbryan** [comment]
@gauravtiwari 

This PR is made as a temporary fix because vue-loader 15 and its new configuration are breaking the default vue pack even on webpacker 4. 

Ultimately, webpacker 4 should use vue-loader 15.

**Comment by michaelize** [comment]
Any ETA on supporting vue-loader 15?

**Comment by gauravtiwari** [comment]
@ytbryan Do you wanna explore how we can integrate v15 in Webpacker 4? I will take a look at this over the weekend.

**Comment by ytbryan** [comment]
@gauravtiwari I tried. 

But even Vue-cli has not fully support webpack 4 and vue-loader 15 yet (just checked that vue-cli latest usess vue-loader 14). Nonetheless, if I figure out something, I will send a PR.

**Comment by WoH** [comment]
I'd be very curious what the issues are you're running into, maybe I missed the description and you can point me towards it. I am using vue-loader 15.0.9, @rails/webpacker 4.0.0-pre.2 and the gem webpacker ~> 4.0.0.pre.pre.2 and I have not run into issues with the default pack as far as I can tell.
I checked the scoped styles and sass.
There should be changes for non-html templates (pug) and probably some non-standard styles + css modules, but a fresh installation of webpacker added the Plugin and the mini-css-extract rules needed.

**Comment by gauravtiwari** [comment]
@WoH Thank you. Happy to make a PR? I guess the styles aren't working out of the box so we should fix that.

**Comment by gauravtiwari** [comment]
Closing this until we have a proper solution for this.

**Pull request closed without merging**
