### PR TITLE
Docs: installation instructions re: unmet peer dependencies

### PR DESCRIPTION
**Pull request by jaredbeck**
See discussion in https://github.com/rails/webpacker/issues/1078

### CODE REVIEW

**Comment by jaredbeck** [comment]
For example, a clean install of webpacker today (2018-05-11) according to the previous instructions results in the following:

```
warning "@rails/webpacker > postcss-cssnext@3.1.0" has unmet peer dependency "caniuse-lite@^1.0.30000697".
warning " > webpack-dev-server@2.11.2" has unmet peer dependency "webpack@^2.2.0 || ^3.0.0".
warning "webpack-dev-server > webpack-dev-middleware@1.12.2" has unmet peer dependency "webpack@^1.0.0 || ^2.0.0 || ^3.0.0".
```

**Comment by chriscarpenter12** [comment]
Can confirm. I just started a new project and couldn't get webpack-dev-server to start. Ran `yarn upgrade` and it worked.

**Comment by jaredbeck** [comment]
Three month ping. This is docs-only, should be a quick review, thanks.

**Comment by gauravtiwari** [comment]
Thanks @jaredbeck and apologies for delay :)

**Pull request merged**
