### PR TITLE
Optional .postcssrc.yml

### PR DESCRIPTION
**Pull request by JakeLaCombe**
Resolves https://github.com/rails/webpacker/issues/1623

Most of the settings that exist in  .postcssrc.yml can be overwritten using JavaScript code. By making these files optional, it makes it easier to create a node package that contains reusable webpacker configurations which can be imported into various Rails applications.

### CODE REVIEW

**Comment by guilleiguaran** [comment]
Can we divide this in two PRs, so we can discuss both files separately?

**Comment by JakeLaCombe** [comment]
I can do that. Would you like separate issues for each as well?

**Comment by guilleiguaran** [comment]
Let's keep just one issue for discussion, I see that the `.postcssrc.yml` have been accepted already but I haven't seen any opinions about the `webpacker.yml` yet.

**Comment by guilleiguaran** [comment]
Please fix the broken tests related to this change (run tests with `yarn test`)

**Comment by JakeLaCombe** [comment]
Sorry about those breaking tests. For some odd reason, it's failing on your travis build, but passing on mine. I'll close this out and send a new one when I have that issue worked out.

**Pull request closed without merging**
